export const API_URL = "https://disease.sh/v3/covid-19";

export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';

export const FETCH_DAILY_DATA = "FETCH_DAILY_DATA";
export const FETCH_DAILY_DATA_SUCCESS = 'FETCH_DAILY_DATA_SUCCESS';
export const FETCH_DAILY_DATA_FAILED = 'FETCH_DAILY_DATA_FAILED';

export const FETCH_COUNTRY_DATA = "FETCH_COUNTRY_DATA";
export const FETCH_COUNTRY_DATA_SUCCESS = 'FETCH_COUNTRY_DATA_SUCCESS';
export const FETCH_COUNTRY_DATA_FAILED = 'FETCH_COUNTRY_DATA_FAILED';

export const FETCH_CHART_DATA = "FETCH_CHART_DATA";
export const FETCH_CHART_DATA_SUCCESS = 'FETCH_CHART_DATA_SUCCESS';
export const FETCH_CHART_DATA_FAILED = 'FETCH_CHART_DATA_FAILED';
